// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYOwRNDNgeWOoUekC6xWsk7mNmB9ZZ5uU',
    appId: '1:37292201382:web:751ff6ec27a36fa8742b67',
    messagingSenderId: '37292201382',
    projectId: 'uvisitfinal',
    authDomain: 'uvisitfinal.firebaseapp.com',
    storageBucket: 'uvisitfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUIojMD1CfnbRUYl8FCY-zwKvuH3V4IE',
    appId: '1:37292201382:android:26c9080276fa7e4e742b67',
    messagingSenderId: '37292201382',
    projectId: 'uvisitfinal',
    storageBucket: 'uvisitfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vPp0t5nz0sB2dRVto37W7z9BCdioixI',
    appId: '1:37292201382:ios:356633e1a2cf70f0742b67',
    messagingSenderId: '37292201382',
    projectId: 'uvisitfinal',
    storageBucket: 'uvisitfinal.appspot.com',
    iosClientId: '37292201382-psh6276iondrsgg4vpijnco8kerhvdhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uvisitfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vPp0t5nz0sB2dRVto37W7z9BCdioixI',
    appId: '1:37292201382:ios:356633e1a2cf70f0742b67',
    messagingSenderId: '37292201382',
    projectId: 'uvisitfinal',
    storageBucket: 'uvisitfinal.appspot.com',
    iosClientId: '37292201382-psh6276iondrsgg4vpijnco8kerhvdhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uvisitfinal',
  );
}
